# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Luis Alcaras
tagline:          'Software Engineer at F5'
description:      'Personal blog by Luis Alcaras, software engineer at F5. Sharing thoughts, experiences, and insights about software development.'
url:              https://luisalcarasr.github.io
baseurl:          /blog

author:
  name:           'Luis Alcaras'
  url:            https://github.com/luisalcarasr

paginate:         5

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/luisalcarasr/blog
