# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Luis Alcaras
tagline:          'Software Engineer at F5'
description:      "Practical lessons on cloud security engineering, resilient data platforms, and full-stack systems built for real-world scale."
url:              https://luisalcarasr.github.io
baseurl:          /blog

author:
  name:           'Luis Alcaras'
  url:            https://github.com/luisalcarasr

paginate:         5

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/luisalcarasr/blog
